POST http://localhost:8000/booking/cargos
Content-Type: application/json
Accept: application/json

{
    "origin": "IDJKT",
    "destination": "IDBDG",
    "deadline": "2023-06-12T00:00:00Z"
}

###

GET http://localhost:8000/booking/cargos
Accept: application/json

###
GET http://localhost:8000/booking/cargos/7820396B
Accept: application/json

###
POST http://localhost:8000/booking/cargos/7820396B/assign_route
Accept: application/json
Content-Type: application/json

{
    "id": 1,
    "legs": [
        {
            "voyage_number": "",
            "from": "IDJKT",
            "to": "IDBDG",
            "load_time": "2023-06-08T00:00:00Z",
            "unload_time": "2023-06-11T00:00:00Z"
        }
    ]
}
